from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from datetime import datetime
import os


class PDFReportGenerator:

    def __init__(self):

        os.makedirs(
            "reports",
            exist_ok=True
        )

    #############################################################

    def mask_aadhaar(self, number):

        if not number:
            return "Not Found"

        digits = number.replace(" ", "")

        if len(digits) != 12:
            return number

        return "XXXX XXXX " + digits[-4:]

    #############################################################

    def generate(self, report):

        filename = f"reports/report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

        doc = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        story = []

        story.append(
            Paragraph(
                "<b><font size=18>PRAMAN</font></b>",
                styles["Title"]
            )
        )

        story.append(
            Paragraph(
                "AI Powered Aadhaar Verification Report",
                styles["Heading2"]
            )
        )

        story.append(Spacer(1, 0.25 * inch))

        story.append(
            Paragraph(
                f"Generated : {datetime.now()}",
                styles["Normal"]
            )
        )

        story.append(Spacer(1, 0.2 * inch))

        aadhaar = report["aadhaar"]
        face = report["face"]
        quality = report["image_quality"]
        tampering = report["tampering"]

        data = [

            ["Status", report["status"]],

            ["Confidence", f'{report["confidence"]}%'],

            ["Name", aadhaar.get("name", "-")],

            ["DOB", aadhaar.get("dob", "-")],

            ["Gender", aadhaar.get("gender", "-")],

            [
                "Aadhaar",
                self.mask_aadhaar(
                    aadhaar.get(
                        "aadhaar_number"
                    )
                )
            ],

            [
                "Image Quality",
                quality["status"]
            ],

            [
                "Face Similarity",
                f'{face["similarity"]}%'
            ],

            [
                "Face Verified",
                str(face["verified"])
            ],

            [
                "Tampering",
                "Detected"
                if tampering["tampered"]
                else "Not Detected"
            ]

        ]

        table = Table(data, colWidths=[2.5 * inch, 3.5 * inch])

        table.setStyle(

            TableStyle([

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),

                ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("ALIGN", (0, 0), (-1, -1), "LEFT")

            ])

        )

        story.append(table)

        story.append(Spacer(1, 0.3 * inch))

        story.append(

            Paragraph(

                "<b>Remarks</b>",

                styles["Heading2"]

            )

        )

        if report["status"] == "PASS":

            remark = "Document appears authentic."

        else:

            remark = "Verification failed. Manual review recommended."

        story.append(

            Paragraph(

                remark,

                styles["Normal"]

            )

        )

        story.append(Spacer(1, 0.5 * inch))

        story.append(

            Paragraph(

                "<i>Generated by PRAMAN AI Verification System</i>",

                styles["Italic"]

            )

        )

        doc.build(story)

        return filename